# Use root/example as user/password credentials
version: '3.3'

services:
  mongo:
    image: mongo
    volumes:
      - ./docker-compose-data/mongodb:/data/db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  # When logging onto the webpage, username is `admin` and password is `pass`.
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001 # Web GUI address
    volumes:
      - ./docker-compose-data/minio:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"

  victoria-metrics:
    image: victoriametrics/victoria-metrics:latest
    ports:
      - 8428:8428
    volumes:
      - ./docker-compose-data/victoria-metrics:/data
    restart: always
    command:
      - -storageDataPath=/data
      - -retentionPeriod=100y

  grafana:
    image: grafana/grafana:latest
    ports:
      - 5000:3000
    volumes:
      - ./docker-compose-data/grafana:/var/lib/grafana
    restart: always
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: pass
      GF_SERVER_ROOT_URL: http://localhost:5000
    user: "$UID:$GID"
    depends_on:
      - victoria-metrics
